### ISSUE TITLE
Wrong CSS for full screen terminal and external terminal

### ISSUE THREAD

**Issue by jcubic** [jcubic/jquery.terminal#1009]
### Issue summary

The library force `height: 100%` when using on body. The problem is when using `.terminal-external` class:

### Steps to reproduce
* https://github.com/jcubic/lips/issues/435

### Browser and OS
N/A

### Additional notes

To fix the issue, there is a need to use this code:

```css
body.full-screen-terminal .terminal:not(.terminal-external) {
    height: 100% !important;
}
```
