### ISSUE TITLE
Unexpected Cursor on IE11/Edge :\

### ISSUE THREAD

**Issue by tejaswirohit** [jcubic/jquery.terminal#344]
### Expected behavior
While typing in the terminal window a second '|' cursor is shown towards the beginning  of the line being typed on. This behavior is observed while using the terminal on Edge/IE11.

### Actual behavior
There should be exactly one cursor right after the last character that was typed.

### Steps to reproduce
1. Open Edge/IE11
2. Start a jquery terminal
3. Begin typing

Video :) [https://i.imgur.com/79fKtau.gifv](https://i.imgur.com/79fKtau.gifv)
### Browser and OS
Browser: Edge/IE11 
OS: Windows 10

**Comment by jcubic** [comment]
Fixed in devel branch, if you want the fix now you can apply this css:

```css
.cmd .clipboard {
    opacity: 0.01;
    filter: alpha(opacity = 0.01);
    filter: progid:DXImageTransform.Microsoft.Alpha(opacity=0.01);
}
```
