### ISSUE TITLE
Use contain: content for better performace

### ISSUE THREAD

**Issue by jcubic** [jcubic/jquery.terminal#377]
This speed up repaint (it don't repaint whole site) when you press enter and terminal need to be updated.

```css
.terminal {
    contain: content;
}
```
