### ISSUE TITLE
Resize Event not triggered in Firefox

### ISSUE THREAD

**Issue by mesurinna** [jcubic/jquery.terminal#395]
The resizing event is not fired correctly in firefox (code Lines 805-807):

{code}

                    $(iframe.contentWindow).on('resize', function() {
                        callbacks.fire();
                    });

{code}

When i resize the window nothing happens, after clicking with mouse with the right button, the view of the terminal is refreshed.

This happens only in Firefox. IE is resizing correctly, and Chrome is using the resizeObserver, as expected.

Someone else experiencing this error? I am running the Terminal in a Iframe, maybe that is the cause of my error?

Kind regards
Tommaso

**Comment by jcubic** [comment]
The fix is in devel branch it will be in next version. To fix this now you can use this css snipped:
```css
.terminal > .resizer, .terminal > .font .resizer {
    visibility: visible;
    pointer-events: none;
}
```
