### ISSUE TITLE
Font-family on universal selector break styling

### ISSUE THREAD

**Issue by jcubic** [jcubic/jquery.terminal#415]
### Expected behavior

this should not affect the terminal:
```css
* {
  font-family: sans-serif
}
```
### Actual behavior

if make font for terminal, that's on the page, sans-serif.

### Steps to reproduce
Check https://yunchaodu.com/
