### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by bilogic** [jcubic/jquery.terminal#473]
### I have question related to jQuery Terminal

Hi,

Is there a quick way to get a white-based/light theme terminal?
Thanks!

**Comment by jcubic** [comment]
Yes, you can use css variables (also called custom properties):
```css
.terminal {
    --background: white;
    --color: black;
}
```
color need to be black because gray (even darkgray) is too white.
