### ISSUE TITLE
[Regresion] Wide character issue

### ISSUE THREAD

**Issue by jcubic** [jcubic/jquery.terminal#535]
### Expected behavior

Wide characters change width of 2 ch

### Actual behavior

The width of the span is only change because character inside, width have no effect. 

### Steps to reproduce

See old pen:

https://codepen.io/jcubic/pen/GQXqVW

**Comment by jcubic** [comment]
The fix look like this:
```css
.cmd span[style], .terminal span[style] {
    display: inline-block;
}
```
Demo have button to check how this affect ASCII table.
