### ISSUE TITLE
Document responsive font size

### ISSUE THREAD

**Issue by jcubic** [jcubic/jquery.terminal#628]
### I have idea for a new feature for jQuery Terminal

In Figlet Pipe demo I've added responsive font size with media queries and `--size` it should be document.
https://codepen.io/jcubic/pen/vYLvvXx?editors=0110

This is important for big screens, default font is way to small for big screens

**Comment by jcubic** [comment]
Alternative is:
```css
@media (min-width: 800px) {
    :root {
        --size: 1.2;
    }
}
@media (min-width: 1200px) {
    :root {
        --size: 1.5;
    }
}
```
