### ISSUE TITLE
Setting Custom Emulator Fonts

### ISSUE THREAD

**Issue by binarypheonix** [jcubic/jquery.terminal#660]
### I have question, related to jQuery Terminal

How do I set a custom font for the entire terminal using fonts from Google fonts?

I've searched as much as I could for this and couldn't find anything.

Is it even possible? Any help would be appreciated...

**Comment by jcubic** [comment]
Unfortunately there is not straightforward way. If you look at css (e.g. using dev tools inspector) you will see this:

```css
.cmd, .cmd span:not(.fas):not(.far):not(.fa), .terminal, .terminal-output>:not(.raw), .terminal-output>:not(.raw) a, .terminal-output>:not(.raw) span:not(.fas):not(.far):not(.fa) {
    font-family: monospace;
}
```
You would need to overwrite this. But not that if you will pick a font that is not monospace you may have problems with line-wrapping. I would need to introduce another CSS variable to make it work with a future version, where this long CSS selector may change.
