### ISSUE TITLE
Custom property for font family

### ISSUE THREAD

**Issue by jcubic** [jcubic/jquery.terminal#662]
### I have an idea for a new feature for jQuery Terminal

It would be nice to be able to change the font with custom property instead of obscure CSS that may change the future versions.

```css
.terminal {
    --font: droid-mono;
}
```
