### ISSUE TITLE
Make terminal fully working with transparent background

### ISSUE THREAD

**Issue by jcubic** [jcubic/jquery.terminal#698]
### I have an idea for a new feature for jQuery Terminal
The idea is to allow:
```css
:root {
  --background: rgba(0, 0, 0, 0.5);
}
```
