### ISSUE TITLE
Empty lines don't show up in prompt

### ISSUE THREAD

**Issue by jcubic** [jcubic/jquery.terminal#734]
### Issue summary

Empty lines are ignored by typing animation

### Expected behavior

Text print properly new lines

### Actual behavior

Text jumps

### Steps to reproduce
1. Open [Gaiman Demo](https://gaiman.js.org/)
2. Enter: `echo* (get "/gaiman.txt"), 5`

**Comment by jcubic** [comment]
The problem is that the prompt can't contain an empty line:

https://codepen.io/jcubic/pen/GRMYwyJ

The fix is to use:

```css
.cmd .cmd-line::before {
    content: "\0200B";
    display: inline-block;
    width: 0;
}
```

The same as with `.terminal-output div` but without `float: left`
