### ISSUE TITLE
bar and underline cursors are  not affected by setting glow 

### ISSUE THREAD

**Issue by jcubic** [jcubic/jquery.terminal#756]
### Issue summary
Glow doesn't work with bar and underline animation cursors

### Expected behavior
All cursors should have glow

### Actual behavior
No glow

### Steps to reproduce
set CSS:
```css
:root {
    --glow: 1;
    --animation: terminal-bar;
}
```

### Browser and OS
All
