### ISSUE TITLE
Integrate prefers-reduced-motion style into the main css

### ISSUE THREAD

**Issue by jcubic** [jcubic/jquery.terminal#799]
### I have an idea for a new feature for jQuery Terminal

You can use:
```css
@media (prefers-reduced-motion) {
    :root {
        --animation: terminal-none;
    }
}
```
It can be added as default.
