### ISSUE TITLE
Add link color transition

### ISSUE THREAD

**Issue by jcubic** [jcubic/jquery.terminal#870]
### I have an idea for a new feature for jQuery Terminal

Small embellishment:

```css
.terminal a[href] {
  transition-property: color, background-color;
  transition-duration: 0.3s;
  transition-timing-function: ease-out;
}
```

from: https://codepen.io/jcubic/pen/xxWgWKz?editors=0110

- [ ] Check for prefers reduced motion
