### ISSUE TITLE
How to customize terminal ui?

### ISSUE THREAD

**Issue by tonmoy998** [jcubic/jquery.terminal#893]
I want to stylize the terminal.And want to add cursor animation.i am beginner so consider helping me.

**Comment by jcubic** [comment]
You can read this Article [CSS-Style](https://github.com/jcubic/jquery.terminal/wiki/CSS-Style) on Wiki. If you're a beginner I don't think I can help you to customize the cursor, you will need to learn CSS and read the code in other to edit the library CSS and add a different animation.

But there are built-in 3 animations. I think that this information is missing on a Wiki.

You can change the animation with CSS variables:

```css
:root {
   --animation: terminal-blink; /* this is default */
   --animation: terminal-underline;
   --animation: terminal-bar;
   --animation: terminal-none; /* no animation */
}
```

What kind of cursor animation do you want to add?

**Comment by tonmoy998** [comment]
I am at intermediate in css.Actually I want blinking animation for input cursor.It's look better

**Comment by tonmoy998** [comment]
Instead of "> " I want to put some test as tittle.

**Comment by jcubic** [comment]
If you want to change "> " it's not a cursor it's the prompt. The cursor is the blinking rectangle. To change the prompt you use the `prompt` option ot use method `set_prompt()`.

But if you want to change the actual cursor to something else you need to look into the library CSS file:

This is how the cursor animation looks like in CSS:

```css
@-webkit-keyframes terminal-blink {
    0%, 50% {
        background-color: #aaa;
        background-color: var(--original-color, #aaa);
        color: #000;
        color: var(--original-background, #000);
        -webkit-box-shadow: 0 0 calc(var(--glow) * 3px) var(--color, #aaa);
        box-shadow: 0 0 calc(var(--glow) * 3px) var(--color, #aaa);
    }
    50.1%, 100% {
        background-color: inherit;
        /* original background is set in emoji that need different style */
        color: inherit;
        color: var(--original-color, #aaa)
    }
}
@-moz-keyframes terminal-blink {
    0%, 50% {
        background-color: #aaa;
        background-color: var(--original-color, #aaa);
        color: #000;
        color: var(--original-background, #000);
        -webkit-box-shadow: 0 0 calc(var(--glow) * 3px) var(--color, #aaa);
        box-shadow: 0 0 calc(var(--glow) * 3px) var(--color, #aaa);
    }
    50.1%, 100% {
        background-color: inherit;
        color: inherit;
        color: var(--original-color, #aaa);
    }
}
@keyframes terminal-blink {
    0%, 50% {
        background-color: #aaa;
        background-color: var(--original-color, #aaa);
        color: #000;
        color: var(--original-background, #000);
        -webkit-box-shadow: 0 0 calc(var(--glow) * 3px) var(--color, #aaa);
        box-shadow: 0 0 calc(var(--glow) * 3px) var(--color, #aaa);
    }
    50.1%, 100% {
        background-color: inherit;
        color: inherit;
        color: var(--original-color, #aaa);
        -webkit-box-shadow: none;
        box-shadow: none;
    }
}
```
