### ISSUE TITLE
How to restore the scroll bar style to the browser default style？

### ISSUE THREAD

**Issue by lingyunzhimeng** [jcubic/jquery.terminal#908]
### I have an idea for a new feature for jQuery Terminal

I have upgraded to the latest version, but I want to use the browser’s default scroll bar. How should I set it up?

**Comment by jcubic** [comment]
There is no easy way, but now when you have container queries with style function I can create a toggle for it with CSS Variable.

**Comment by jcubic** [comment]
Unfortunately, style container queries don't work in Chrome. I've reported a bug:

https://bugs.chromium.org/p/chromium/issues/detail?id=1512309

So in order to use default scrollbar you need to delete this CSS:

```css
    .terminal-scroller::-webkit-scrollbar {
        background: var(--background, #000);
    }
    .terminal-scroller::-webkit-scrollbar-thumb {
        background: var(--color, #aaa);
    }
    .terminal-scroller::-webkit-scrollbar-thumb:hover {
        background: var(--color, #aaa);
    }
    .terminal-scroller {
        scrollbar-color: #aaa #000;
        scrollbar-color: var(--color, #aaa) var(--background, #000);
        scrollbar-width: thin;
    }
```
