### ISSUE TITLE
Make it easy to set fixed number of rows

### ISSUE THREAD

**Issue by jcubic** [jcubic/jquery.terminal#956]
### I have an idea for a new feature for jQuery Terminal

This just come out, the ASCII Star Wars demo show scrollbar because it has a wrong height.

![Przechwycenie obrazu ekranu_2024-07-24_01-57-48](https://github.com/user-attachments/assets/87382379-5999-44a1-bcf1-c4dcdf22b3cb)

It requires 14 lines to not show overflow.

It would be nice to have a way to set 14 rows that will adapt to the size of the terminal:

```css
#term {
    --terminal-line: calc(var(--size, 1) * (16px / var(--pixel-density, 1)) + 1px / var(--pixel-density, 1));
    height: calc((var(--terminal-line) * 14) + 20px);
}
```

`--terminal-line` rule taken from line-height on output line.

**Comment by jcubic** [comment]
Instead of fixed 14 we can use another CSS variable:

```css
:root {
   --size: 1.2;
   --terminal-rows: 14;
}

.terminal {
    height: calc((var(--terminal-line) * var(--terminal-rows)) + 20px);
}
```
