### ISSUE TITLE
Hover style of links on transparent background

### ISSUE THREAD

**Issue by jcubic** [jcubic/jquery.terminal#990]
### Issue summary

when using transparent background, the links text is not visible on hover

### Expected behavior
Text should be always visible

### Steps to reproduce
1. Open Demo https://codepen.io/jcubic/pen/dPbpvPm
2. Hover over link

### Additional notes

This can be fixed with:

```css
.terminal a:hover {
  --base-background: black;
}
```

Not sure if this can be fixed. This may be added into documentation.
